### ISSUE TITLE
cljs-repl

### ISSUE THREAD

**Issue by yenda** [danielsz/holygrail#4]
I am wondering how one can use the cljs-repl with this workflow. Reading the console logs I noticed that a ws is opened, but when I start a cljs repl in the repl with (cljs-repl) - (start-repl) it is using a new ws and the repl doesn't seem to interact with the browser.

Thank you for this interesting workflow, it even help me to get started with boot.

**Comment by danielsz** [comment]
Hello @yenda. I've added a task to help you get started with boot-cljs-repl. I hope this helps.

**Comment by yenda** [comment]
Thank you I will try it asap in a personnal project. For now I'm using only the server part and doing the cljs stuff in a separated project with om-next.
