### ISSUE TITLE
Boot template based on holygrail

### ISSUE THREAD

**Issue by shakdwipeea** [danielsz/holygrail#7]
It could be a good idea for having a boot template to generate this project. I found myself time and again cloning this repo then chaning the namespaces. 
Is there a better alternative to scaffold a project with system ?

**Comment by danielsz** [comment]
Hi, 
You can look into https://github.com/boot-clj/boot-new, which is geared towards scaffolding and generating projects from templates. 
Personally I'm not a big fan of project templates, but if you get good results, I'll provide a link to your repo. Thanks!

**Comment by shakdwipeea** [comment]
I'll try to look into it when I get some time, will post link here if I get it working. Feel free to close this for now.

**Comment by danielsz** [comment]
Sounds good. Thanks, @shakdwipeea

**Comment by shakdwipeea** [comment]
Sth I am working on for generating initial setup for clj and cljs. https://github.com/shakdwipeea/system-template

**Comment by danielsz** [comment]
Nice!
Are you satisfied with it? Do you think it's ready for others to try it out?
Please let me know when I can add a link to the README. Thank you.

**Comment by shakdwipeea** [comment]
I think it's ready for people to try out. I've just done a release.

**Comment by danielsz** [comment]
I've updated the README of system with a reference to your project. https://github.com/danielsz/system#the-holy-grail

Thanks again!
